name: CI

on: push

env:
  FILE_PATH_BOILERPLATE_APP_VERSION_INFO: ./apps/boilerplate-app/src/common/version/VersionInfo.ts
  FILE_PATH_BOILERPLATE_APP_BUILD_NEXT: './apps/boilerplate-app/build-next-static'

  FILE_PATH_BOILERPLATE_WEBSITE_VERSION_INFO: ./apps/boilerplate-website/src/common/version/VersionInfo.ts
  FILE_PATH_BOILERPLATE_WEBSITE_BUILD_NEXT: './apps/boilerplate-website/build-next-static'

jobs:
  build:
    name: Build 🏗️
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

      - name: Version Info 💉
        run: |
          COMMIT=$GITHUB_SHA
          BRANCH=${GITHUB_REF#refs/heads/}
          TAG=''
          if [[ ${{ github.ref_type }} == 'tag' ]]; then
            TAG=${GITHUB_REF#refs/tags/}
          fi
          echo "write tag, branch & commit id to $FILE_PATH_BOILERPLATE_APP_VERSION_INFO"
          echo "export const VersionInfo = { tag: '$TAG', branch: '$BRANCH', commit: '$COMMIT' };" > $FILE_PATH_BOILERPLATE_APP_VERSION_INFO
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Build 🏗️
        run: npm run build

      - name: Cache build ⚡
        id: cache_build
        uses: actions/cache@v3
        with:
          path: $FILE_PATH_BOILERPLATE_APP_BUILD_NEXT
          key: build_app_next

  # lint:
  #   name: Lint ✅
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Lint ✅
  #       run: npm run lint

  # tsc:
  #   name: tsc 🔎
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: tsc 🔎
  #       run: npm run tsc

  # test:
  #   name: Test 🧪
  #   needs: build
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout 🛎️
  #       uses: actions/checkout@v3

  #     - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
  #       uses: ./.github/workflows/actions/setup_node-cache_dep-install_dep

  #     - name: Test 🧪
  #       run: npm run test

  deploy-stage:
    name: Deploy Stage 🚀
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    environment:
      name: App Stage
      url: https://turbo-app-stage.netlify.app

    steps:
      - uses: actions/cache@v3
        with:
          path: $FILE_PATH_BOILERPLATE_APP_BUILD_NEXT
          key: build_app_next

      - name: Version Info 💉
        run: |
          echo "pwd"
          pwd
          echo "ls"
          pwd
          cat $FILE_PATH_BOILERPLATE_APP_VERSION_INFO

      - name: Deploy Stage 🚀
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './apps/boilerplate-app/build-next-static'
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_STAGE_BOILERPLATE_APP }}

  deploy-prod:
    name: Deploy Production 🚀
    # needs: [build, lint, tsc, test]
    needs: build
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'

    environment:
      name: App Prod
      url: https://turbo-app-prod.netlify.app/

    steps:
      - name: Deploy Production 🚀
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: $FILE_PATH_BOILERPLATE_APP_BUILD_NEXT
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID_PROD_BOILERPLATE_APP }}
